version: "3.5"
services: 
  consul: 
    image: consul
    restart: always
    networks: 
      - quizrt-gateway-network
  gateway: 
    build:
      context: ./Gateway
    depends_on: 
      - consul
      - registrator
    networks: 
      - quizrt-gateway-network
  registrator: 
    image: gliderlabs/registrator
    restart: always
    volumes: 
      - "/var/run/docker.sock:/tmp/docker.sock"
    depends_on:
      - consul
    networks: 
      - quizrt-gateway-network
    command: "-internal consul://consul:8500"
networks:
  quizrt-gateway-network:
    name: quizrt-network