--- 
services: 
  consul: 
    image: consul
    restart: always
  gateway: 
    build: 
      context: ./Gateway
    depends_on: 
      - consul
      - registrator
    network_mode: host
  registrator: 
    image: gliderlabs/registrator
    # network_mode: host
    restart: always
    volumes: 
      - "/var/run/docker.sock:/tmp/docker.sock"
    depends_on:
      - consul
    command: "-internal consul://consul:8500"
version: "3"
